add instructions for ios (adguard)
autinerd/anti-axelspringer-hosts pull request #9
Opened 2020-09-23 10:59 UTC by marudor

AdGuard ist mein Content Blocker der Wahl - Custom Rules gehen leider nur bezahlt. Aber man kann einfach User Rules hinzufügen. Er will dabei zwingend .txt dateien - darum hab ich noch mal eine extra Datei generiert (dein python skript erstellt sie jetzt auch)

2020-09-24 15:35 UTC, autinerd requested changes
Nach der Korrektur des Rechtschreibfehlers passt es :) braucht AdGuard kein www.? Dann ist alles wunderbar.

2020-09-24 15:35 UTC, autinerd commented on README.md
> +Nicht vergesse den Content Blocker für Safari zu aktivieren
Rechtschreibfehler

2020-09-26 10:08 UTC, marudor commented
Adguard braucht kein www. Typo fixed.

2020-09-27 15:49 UTC, autinerd approved these changes

2020-09-27 15:49 UTC, merged

2020-09-27 15:50 UTC, autinerd commented
Vielen Dank für die Hilfe!